version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client_manager
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/client_manager
    ports:
      - '3001:3001'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - '3000:3000'

volumes:
  db-data:
